# Generated by Django 4.1.7 on 2023-03-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_product_comment_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='video',
            new_name='video_id',
        ),
    ]
