# Generated by Django 4.1.7 on 2023-03-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_user_avatar_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='uploadImage/2023/03/defaultAvatar_3.png', null=True, upload_to='uploadImage/%Y/%m'),
        ),
    ]
