# Generated by Django 4.1.7 on 2023-03-25 07:44

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=backend.models.default_product_image, null=True, upload_to='uploadImage/%Y/%m'),
        ),
    ]
