# Generated by Django 4.1.7 on 2023-03-25 07:47

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=backend.models.default_product_image, null=True, upload_to=backend.models.default_product_image),
        ),
    ]
